"""
build_catalog.py -- generates catalog.json, the 47-requirement DPDP framework.

RECONSTRUCTION NOTE (2026-08-19): the original catalog.json was lost with E:\Adhikar.
This file is rebuilt from two authoritative sources that survived:
  1. Two real engine-generated reports (Compliance + Recommendation for cyberpeace.org)
     which give every requirement, DPDP anchor, category, severity, penalty band and
     the exact finding/remediation wording.
  2. The engine internals read verbatim from the working session (field schema, verdict
     labels, weights, grade thresholds).
The `signals` keyword lists are RECONSTRUCTED (the originals were data, not in any report);
they are faithful to each requirement's meaning and can be tuned. Everything else is
grounded in the reports.

Penalty bands (DPDP Schedule, via Appendix C of the report):
  security        up to 250 crore   (Act S.8(5); Rule 6)
  breach_notify   up to 200 crore   (Act S.8(6); Rule 7)
  children        up to 200 crore   (Act S.9)
  sdf             up to 150 crore   (Act S.10; Rule 12/13)
  other_provision up to  50 crore   (notice/consent/purpose/retention/rights/grievance/cross-border)
  good_practice   no statutory penalty (recommended practice)
"""
import json
from pathlib import Path

PENALTY_MAX = {
    "security": "up to 250 crore",
    "breach_notify": "up to 200 crore",
    "children": "up to 200 crore",
    "sdf": "up to 150 crore",
    "other_provision": "up to 50 crore",
    "good_practice": "no statutory penalty (recommended practice)",
}

# id, category, requirement (positive), finding (negative, for the report),
# act_section, rule, severity, mandatory, disclosure_only, observed, penalty_band,
# min_strong, strong signals, remediation, impact
C = [
 (1,"Consent & Notice","The notice itemises the categories of personal data collected, in plain language.",
   "The notice does not itemise the personal data collected","S.5","Rule 3","High",True,False,None,"other_provision",2,
   ["categories of personal data","information we collect","data we collect","personal data collected","name, email","types of information"],
   "Add a short notice and consent line at the point of collection, listing the data fields taken.",
   "Individuals cannot know what data is taken from them."),
 (2,"Consent & Notice","A specific purpose is stated for the data collected; generic 'business purposes' is only Partial.",
   "No specific purpose is stated for the data collected","S.6","Rule 3","High",True,False,None,"other_provision",1,
   ["purpose of collection","purpose for which","we use your data to","in order to","for the purpose of"],
   "State the purpose for each field and collect only what it needs.",
   "Data may be used for purposes the individual never agreed to."),
 (3,"Consent & Notice","The notice is clear, plain-language and understandable on its own.",
   "The notice is not written in plain, self-contained language","S.5","Rule 3","High",True,False,None,"other_provision",1,
   ["privacy policy","privacy notice","this policy explains","plain language"],
   "Publish a dated, plain-language privacy notice that stands on its own.",
   "A notice that cannot be understood does not give real notice."),
 (4,"Lawful Basis & Purpose Limitation","Processing is on a stated lawful basis (consent or a legitimate use).",
   "No lawful basis is stated for the processing","S.4",None,"High",True,False,None,"other_provision",1,
   ["lawful basis","legal basis","with your consent","legitimate use","basis for processing"],
   "State the lawful basis (consent or a specific legitimate use) for each processing purpose.",
   "Processing without a stated basis is unlawful under the Act."),
 (5,"Lawful Basis & Purpose Limitation","Collection is limited to data necessary for the specified purpose (purpose/data limitation).",
   "Data is collected without minimisation to the stated purpose","S.6(1)",None,"High",True,False,None,"other_provision",1,
   ["only collect","data minimisation","necessary for","limited to what","minimum necessary"],
   "Collect only the fields the stated purpose needs; drop the rest.",
   "Excess collection increases the harm if the data is breached."),
 (6,"Lawful Basis & Purpose Limitation","If legitimate uses are relied upon, they fall within the Act's Section 7 categories.",
   "Any legitimate use relied upon is not mapped to Section 7","S.7",None,"Low",False,False,None,"other_provision",1,
   ["legitimate use","section 7","specified purpose","voluntary provision"],
   "Map any legitimate use to a Section 7 category, or rely on consent instead.",
   "A legitimate use outside Section 7 has no lawful footing."),
 (7,"Data Quality & Retention","A commitment to keep personal data accurate, complete and up to date.",
   "No commitment to keep personal data accurate and up to date","S.8(3)",None,"Medium",False,False,None,"other_provision",1,
   ["accurate","up to date","keep your information current","correct and complete"],
   "Commit to keep personal data accurate and offer a way to update it.",
   "Decisions made on stale data can harm the individual."),
 (8,"Data Quality & Retention","A retention period, or an 'erase when the purpose ends' commitment, is stated.",
   "No retention or erasure schedule is stated","S.8(7)-(8)","Rule 8","High",True,False,None,"other_provision",1,
   ["retention period","retain","how long we keep","erase when","data retention","delete your data","retention schedule"],
   "Publish retention periods per record type and erase when the purpose ends.",
   "Data kept indefinitely is a standing liability."),
 (9,"Security & Breach Response","Reasonable security safeguards (encryption, access control) are disclosed.",
   "The security safeguards protecting personal data are not described","S.8(5)","Rule 6","High",True,False,None,"security",1,
   ["security measures","encryption","access control","safeguards","we protect your data","secure servers","reasonable security"],
   "Describe the reasonable security safeguards that protect personal data.",
   "Undisclosed or absent safeguards leave personal data exposed."),
 (10,"Security & Breach Response","A commitment to notify affected users and the Board of a personal-data breach.",
   "No commitment to notify a personal-data breach","S.8(6)","Rule 7","High",True,False,None,"breach_notify",1,
   ["data breach","breach notification","notify you","inform the board","security incident","in the event of a breach"],
   "Commit to notify affected users and the Board within 72 hours of a breach.",
   "Without a breach commitment, individuals may never learn their data leaked."),
 (11,"Consent Management","Withdrawal of consent is offered and is as easy as giving it, with a route stated.",
   "Consent cannot be withdrawn as easily as it was given","S.6(4)","Rule 3","Medium",True,False,None,"other_provision",1,
   ["withdraw consent","withdraw your consent","opt out","unsubscribe","revoke consent"],
   "Offer a withdrawal route as easy as giving consent, and state it in the notice.",
   "Consent that cannot be withdrawn is not real consent."),
 (12,"Consent Management","Consent is a clear affirmative action, unbundled, not pre-ticked or implied.",
   "Consent is implied, not a clear affirmative opt-in","S.6",None,"Medium",True,False,None,"other_provision",1,
   ["i agree","i consent","opt in","affirmative","tick to consent","by checking this box"],
   "Take consent by a clear affirmative, unbundled action; never pre-tick or imply it.",
   "Implied or bundled consent is invalid under the Act."),
 (13,"Consent Management","The Consent Manager route is acknowledged where relevant.",
   "The Consent Manager route is not acknowledged","S.6(7)","Rule 4","Medium",False,False,None,"other_provision",1,
   ["consent manager","manage your consent","consent dashboard"],
   "Acknowledge the registered Consent Manager route where relevant.",
   "Individuals lose a channel the Act gives them to manage consent."),
 (14,"Consent Management","Users can review consent given / records of consent are maintained.",
   "People cannot review the consent they have given","S.6(6)",None,"Low",False,False,None,"other_provision",1,
   ["review your consent","record of consent","consent history","manage preferences"],
   "Let users review the consent they gave and keep records of it.",
   "Without records, neither side can prove what was agreed."),
 (15,"Child Data Protection","Verifiable parental consent for under-18s, and no tracking, behavioural monitoring or targeted ads to children.",
   "Children's data is not protected as the Act requires","S.9",None,"High",True,False,None,"children",1,
   ["parental consent","under 18","children","guardian consent","age verification","minors"],
   "Take verifiable parental consent; never track, profile or target ads to minors.",
   "Children's data carries the Act's highest protection and penalties."),
 (16,"Data Principal Rights","The right to access a summary of personal data being processed is disclosed.",
   "People cannot ask to see the data held about them","S.11",None,"High",True,False,None,"other_provision",1,
   ["right to access","request a copy","access your data","see the data we hold","summary of personal data"],
   "Add a rights section stating the exact route to request access.",
   "Individuals cannot exercise a right they are not told they have."),
 (17,"Data Principal Rights","The right to correction of personal data is disclosed.",
   "People cannot ask for their data to be corrected","S.12",None,"High",True,False,None,"other_provision",1,
   ["right to correction","correct your data","rectify","update your information"],
   "State the right to correction and how to exercise it.",
   "Uncorrectable errors persist and compound harm."),
 (18,"Data Principal Rights","The right to erasure of personal data is disclosed.",
   "People cannot ask for their data to be erased","S.12",None,"High",True,False,None,"other_provision",1,
   ["right to erasure","right to be forgotten","delete your data","erase your data","request deletion"],
   "State the right to erasure and how to exercise it.",
   "Data that cannot be erased outlives its lawful purpose."),
 (19,"Data Principal Rights","A readily available grievance-redressal route is disclosed.",
   "There is no clear route to raise a grievance","S.13",None,"High",True,False,None,"other_provision",1,
   ["grievance","complaint","raise a concern","grievance officer","redressal",
    "nodal officer","grievance redressal","ombudsman","raise a complaint","complaint officer",
    "escalation matrix","how to complain","lodge a complaint","grievance mechanism"],
   "Publish a grievance-redressal route with a contact and a process.",
   "Individuals have no path to challenge misuse."),
 (20,"Data Principal Rights","The right to nominate is disclosed.",
   "The right to nominate another person is not disclosed","S.14",None,"Medium",False,False,None,"other_provision",1,
   ["right to nominate","nominate","nominee"],
   "Disclose the right to nominate another person to exercise rights.",
   "The nomination right the Act grants goes unused."),
 (21,"Data Protection Officer / contact","A reachable grievance officer or business contact for data queries is published.",
   "No data-protection contact is published on the site","S.8(9)-(10), S.13",None,"High",True,False,None,"other_provision",1,
   ["contact us","data protection officer","dpo","grievance officer","privacy@","email us",
    "nodal officer","privacy officer","reach us","write to us","for any queries",
    "customer care","support@","contact our"],
   "Publish a named DPO or grievance contact with a working email.",
   "There is no one for an individual to reach about their data."),
 (22,"Data Protection Officer / contact","A Data Protection Officer is appointed and published (Significant Data Fiduciary).",
   "No Data Protection Officer is named","S.10","Rule 13","Low",False,True,None,"sdf",1,
   ["data protection officer","dpo","appointed a"],
   "If designated an SDF, appoint and publish a Data Protection Officer.",
   "SDF obligations require a named, reachable DPO."),
 (23,"Processor Accountability","Processors engaged only under a valid contract.",
   "Processors are not shown to be engaged under a written contract","S.8(2)",None,"Low",False,True,None,"other_provision",1,
   ["data processing agreement","processor contract","under contract","bound by contract"],
   "Engage processors only under a written contract and state this.",
   "Uncontracted processors handle personal data without duties."),
 (24,"Processor Accountability","Third parties / recipients of data sharing are disclosed.",
   "The categories of third parties receiving data are not disclosed","S.8(2)",None,"Medium",False,False,None,"other_provision",1,
   ["third parties","share your data with","recipients","we share with","service providers"],
   "Disclose the categories of third parties that receive personal data.",
   "Individuals cannot see where their data flows."),
 (25,"Processor Accountability","Sub-processor oversight is addressed.",
   "Oversight of sub-processors is not addressed","S.8(2)","Rule 6","Low",False,True,None,"security",1,
   ["sub-processor","sub processors","onward transfer oversight"],
   "Address oversight of any sub-processors your processors use.",
   "Unsupervised sub-processors are an unmanaged risk."),
 (26,"Processor Accountability","Security obligations flow down to processors.",
   "Security obligations are not shown to flow down to processors","S.8(2)","Rule 6","Low",False,True,None,"security",1,
   ["flow down","processor security","same security obligations","impose security"],
   "Flow your security obligations down to processors by contract.",
   "A processor without security duties is a weak link."),
 (27,"Cross-border Transfers","Transfers of personal data outside India are disclosed.",
   "Overseas processing of personal data is not disclosed","S.16",None,"Medium",False,False,None,"other_provision",1,
   ["transfer outside india","international transfer","overseas","cross-border","stored outside india"],
   "Disclose whether and where personal data is transferred outside India.",
   "Undisclosed overseas flows evade the Act's transfer controls."),
 (28,"Cross-border Transfers","Compliance with any restricted-country notification is addressed.",
   "Compliance with restricted-country notifications is not addressed","S.16",None,"Low",False,False,None,"other_provision",1,
   ["restricted country","permitted countries","transfer restrictions"],
   "Address compliance with any restricted-country notification.",
   "Transfers to restricted countries may be unlawful."),
 (29,"Cross-border Transfers","Data storage location is disclosed.",
   "Where personal data is stored is not disclosed","S.16",None,"Low",False,False,None,"other_provision",1,
   ["data is stored","hosted in","servers located","storage location","data centre"],
   "Disclose where personal data is stored and hosted.",
   "Individuals cannot judge the jurisdiction their data sits in."),
 (30,"Privacy Engineering","A Data Protection Impact Assessment is undertaken (Significant Data Fiduciary).",
   "No Data Protection Impact Assessment is evidenced for high-risk processing","S.10","Rule 13","Low",False,True,None,"sdf",1,
   ["data protection impact assessment","dpia","impact assessment"],
   "If an SDF, undertake and evidence a Data Protection Impact Assessment.",
   "High-risk processing without a DPIA is unassessed risk."),
 (31,"Privacy Engineering","Privacy by design and periodic audit are addressed.",
   "Privacy by design and periodic audit are not addressed","S.8","Rule 13","Low",False,True,None,"sdf",1,
   ["privacy by design","data protection by design","periodic audit","independent audit"],
   "Address privacy by design and periodic independent audit.",
   "Without design controls and audit, gaps go undetected."),
 (32,"Privacy Engineering","Data-minimisation measures by design are addressed.",
   "Data minimisation by design is not addressed","S.8",None,"Low",False,False,None,"other_provision",1,
   ["minimisation by design","collect only","privacy defaults","data minimization"],
   "Build data minimisation into the collection design.",
   "Over-collection by default multiplies breach harm."),
 (33,"Privacy Documentation","A published privacy policy exists and is reachable.",
   "There is no clear, reachable privacy notice on the site","S.5","Rule 3","High",True,False,None,"other_provision",1,
   ["privacy policy","privacy notice","data protection policy"],
   "Publish a dated privacy policy and link it from every page.",
   "There is no reliable public record of how personal data is handled."),
 (34,"Privacy Documentation","A cookie policy / tracker disclosure is published.",
   "No cookie or tracker disclosure is published","S.5","Rule 3","Medium",False,False,None,"other_provision",1,
   ["cookie policy","cookies","tracking technologies","tracker disclosure","we use cookies"],
   "Publish a cookie/tracker disclosure listing what loads and why.",
   "Trackers run without the disclosure the Act expects."),
 (35,"Privacy Documentation","Terms of service are published.",
   "No terms of service are published","S.5",None,"Low",False,False,None,"other_provision",1,
   ["terms of service","terms and conditions","terms of use"],
   "Publish terms of service alongside the privacy notice.",
   "The terms governing the relationship are undocumented."),
 (36,"Privacy Documentation","Notice is available in an accessible form (and Indian languages where relevant).",
   "The notice is not offered in an accessible form or in Indian languages","S.5","Rule 3","Low",False,False,None,"other_provision",1,
   ["available in","languages","accessible","hindi","regional language"],
   "Offer the notice in an accessible form and relevant Indian languages.",
   "A notice only some can read excludes the rest."),
 (37,"Privacy Documentation","Registered office / entity contact details are published.",
   "The registered office and entity contact details are not published","S.8(9)",None,"Medium",False,False,None,"other_provision",1,
   ["registered office","registered address","cin","our address","head office"],
   "Publish the registered office and entity contact details.",
   "The accountable legal entity is not identifiable."),
 (38,"Technical Controls","The site serves over HTTPS (encryption in transit).",
   "The site is not served over HTTPS","S.8(5)","Rule 6","High",True,False,"https","security",1,
   [],
   "Serve the whole site over HTTPS with a valid certificate.",
   "Data entered on plain HTTP can be read in transit."),
 (39,"Technical Controls","Encryption at rest is disclosed.",
   "Encryption of data at rest is not disclosed","S.8(5)","Rule 6","Low",False,True,None,"security",1,
   ["encryption at rest","encrypted storage","data encrypted"],
   "Disclose that personal data is encrypted at rest.",
   "Stored data without disclosed encryption is a gap."),
 (40,"Technical Controls","Access controls and logging are disclosed.",
   "Access controls and logging are not disclosed","S.8(5)","Rule 6","Low",False,True,None,"security",1,
   ["access control","access logging","audit log","role-based access"],
   "Disclose access controls and logging over personal data.",
   "Unlogged, unrestricted access cannot be held to account."),
 (41,"Governance & Training","An internal data-protection policy / governance is in place.",
   "No internal data-protection governance is evidenced","S.8",None,"Low",False,True,None,"good_practice",1,
   ["internal policy","governance","data protection policy","privacy programme"],
   "Put an internal data-protection policy and governance in place.",
   "Without governance, compliance is ad hoc."),
 (42,"Governance & Training","Staff are trained on data protection.",
   "Staff handling personal data are not shown to be trained","Rule 13",None,"Low",False,True,None,"good_practice",1,
   ["staff training","trained on data protection","awareness training","employee training"],
   "Train staff who handle personal data and evidence it.",
   "Untrained staff are the most common cause of breaches."),
 (43,"Governance & Training","Records of processing activities are maintained.",
   "No records of processing activities are evidenced","S.8",None,"Low",False,True,None,"good_practice",1,
   ["records of processing","ropa","processing register"],
   "Maintain records of processing activities.",
   "Without records, the organisation cannot show what it does."),
 (44,"Governance & Training","An incident-response plan exists.",
   "No incident-response plan is evidenced","S.8(6)","Rule 7","Low",False,True,None,"breach_notify",1,
   ["incident response","incident response plan","breach response","security incident plan"],
   "Maintain an incident-response plan for personal-data breaches.",
   "An unrehearsed breach response fails when it is needed."),
 (45,"Governance & Training","Vendor / third-party risk management is addressed.",
   "Vendor and third-party risk management is not addressed","Rule 6",None,"Low",False,True,None,"security",1,
   ["vendor risk","third-party risk","supplier assessment","vendor management"],
   "Assess and manage vendor and third-party risk.",
   "Unmanaged vendors inherit access without scrutiny."),
 (46,"Governance & Training","Significant-Data-Fiduciary obligations / Board reporting are addressed where applicable.",
   "Significant Data Fiduciary obligations are not addressed","S.10","Rule 13","Low",False,True,None,"sdf",1,
   ["significant data fiduciary","board reporting","sdf obligations"],
   "If designated an SDF, address the enhanced obligations and Board reporting.",
   "SDF duties left unaddressed are a direct breach."),
 (47,"Governance & Training","A periodic compliance review / audit is performed.",
   "No periodic compliance review or audit is evidenced","Rule 13",None,"Low",False,True,None,"sdf",1,
   ["periodic review","compliance audit","annual review","compliance review"],
   "Perform and evidence a periodic compliance review or audit.",
   "Compliance drifts without periodic review."),
]

def anchor(act, rule):
    a = {}
    if rule: a["rule"] = rule
    if act: a["act_section"] = act
    return a

checks = []
for (cid,cat,req,finding,act,rule,sev,mand,donly,obs,band,mins,strong,remed,impact) in C:
    ch = {
        "id": cid, "category": cat, "requirement": req, "finding": finding,
        "dpdp_anchor": anchor(act, rule),
        "primary": "rule" if rule and not act else "act",
        "priority": sev, "penalty_band": band, "penalty_max": PENALTY_MAX[band],
        "mandatory": mand, "disclosure_only": donly, "min_strong": mins,
        "signals": {"strong": strong, "generic": []},
        "remediation": remed, "impact": impact,
        "in_force": "2027-05-14",
    }
    if obs: ch["observed"] = obs
    checks.append(ch)

out = {"framework": "DPDP Act 2023 + DPDP Rules 2025", "version": "1.0-reconstructed",
       "n_checks": len(checks),
       "categories": list(dict.fromkeys(c["category"] for c in checks)),
       "penalty_bands": PENALTY_MAX, "checks": checks}

p = Path(__file__).resolve().parent / "catalog.json"
p.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"wrote {p} : {len(checks)} checks, {len(out['categories'])} categories")
print("mandatory:", sum(1 for c in checks if c['mandatory']),
      "| disclosure_only:", sum(1 for c in checks if c['disclosure_only']))
